### PR TITLE
Fix for missing SSE bitwise not on Intel compilers

### PR DESCRIPTION
**Pull request by kdmurray91**

### CODE REVIEW

**Comment by MikkelSchubert** [comment]
Thanks for the patch!

**Comment by kdmurray91** [comment]
No worries @MikkelSchubert -- though would it be possible for you to make a new tagged release (incorporating this and the windowed trimming feature)?

**Comment by MikkelSchubert** [comment]
Sure. I'll try to get it done today.

**Comment by MikkelSchubert** [comment]
A tagged release (2.2.2) with your pull-request has now been released.
Once again, thanks for the patch.

**Comment by kdmurray91** [comment]
Thanks very much @MikkelSchubert !

**Pull request merged**
