### PR TITLE
Added Architecture "ppc64le"

### PR DESCRIPTION
**Pull request by dthadi3**
Thanks for the code, its working good.

## What do these changes do?

Added Architecture "ppc64le"

## Are there changes in behavior for the user?

No

### CODE REVIEW

**Comment by MikkelSchubert** [comment]
Thank you for the patch.

However, it is unclear to me what the motivation for this change is.
Are anyone actually using AdapterRemoval on this architecture?

Moreover, it looks like your patch replaces the default arch (amd64), rather than adding ppc64le to the list of architectures to test.

Best,
 Mikkel

**Comment by dthadi3** [comment]
Added power support for the travis.yml file with ppc64le. This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing. For more info tag @gerrith3.

**Comment by dthadi3** [comment]
Thank you Mikkel for letting know.

just added back the default arch (amd64) and ppc64le as well, please have a look.

**Comment by gerrith3** [comment]
@MikkelSchubert I'll have to check if we have users - hard to tell but this is in the ppc64le distro of Ubuntu and we do have people doing things like Gene Sequencing and such but I don't know off the top if they use this package.  I'll see if i can find out but no promises.

**Pull request merged**
